### ISSUE TITLE
Internal Server Error since UI Relaunch

### ISSUE THREAD

**Issue by calcosta** [mirkowein/moneymoney-whitebox#7]
Since the latest UI relaunch, account refresh fails with an internal server error.
Login seems to work fine but fetching statements fails:

```
1> Lade Kontostand und Umsätze für Konto xxx ...
1> Getting transactions since 17.05.2020...
1> Sending: GET https://inside.whitebox.eu/goals/xxx/statements?statements_query%5Bstart_date%5D=17.05.2020
1> The server responded with the error message: Internal Server Error. Retrying...
1> Sending: GET https://inside.whitebox.eu/goals/xxx/statements?statements_query%5Bstart_date%5D=17.05.2020
1> HTTPS response: Internal Server Error
1> Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.
```

Any idea how to fix this?

**Comment by mirkowein** [comment]
Hi Simon,

you're right, they changed their design. Since the Extension is web scapping most of the the code has to be rewritten. And Whitebox is sending json with html in it. You have catch the right tags. 
Long story short, i'm already working on a fix and spend already several days to get it working again. 
It also has to get the signature from Money Money. 

kind regards
Mirko

**Comment by mirkowein** [comment]
1.07 Fix is online. Signed by Money Money. 
I was asked how to donate -> [README.md](https://github.com/mirkowein/moneymoney-whitebox/blob/master/README.md)
